Canon/src/Arithmetic/Arithmetic.qs

As of 0.3, controlled adjoint auto is properly resolved to "self" if adjoint self is specified (and vice versa). At the same time I am about to enforce some consistency rules for self adjoint operations, such that this code would become invalid.

removing soon-to-be invalid user defined specializations

---

Canon/src/Arrays/Arrays.qs
Canon/src/Asserts/QuantumAsserts.qs
Canon/src/Combinators/Bind.qs
Canon/src/Data/GeneratorRepresentation.qs
Canon/src/Enumeration/Fold.qs
Canon/src/Enumeration/Map.qs
Canon/src/Math/Functions.qs
Canon/src/PhaseEstimation/Types.qs
Canon/src/Qecc/Types.qs
Canon/src/StatePreparation/QuantumROM.qs
Canon/src/StatePreparation/StatePreparation.qs
Canon/src/StatePreparation/UniformSuperposition.qs
Canon/src/Utils/Paulis.qs

Standalone "# Example" tag is currently ignored by the parser; the currently supported syntax is "# Remarks / ## Example"

Fix "# Example" tag in documentation comments

---

Canon/src/StatePreparation/StatePreparation.qs
Canon/src/StatePreparation/UniformSuperposition.qs

* Fix lower bound in the formula for PrepareUniformSuperposition
* Fix broken formulas in StatePreparation (#280)
* Fix Q# code example in StatePreparationComplexCoefficients (#280)

Fix several formulas in the documentation

---

Build/step-build-libs.yml
Build/step-build-python.yml

Builds have been failing with an error about conda unable to connect due to SSL certificate. Looks to be a Windows-specific problem for conda with Python 3.7. Trying using Pyton 3.6 as that has been reported to fix the problem.

Using Python 3.6

---

Interoperability/python/src/qsharp/serialization.py

The result of an operation returning UDT was showing in Python like this:
```
{'@type': 'Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerEncodingData', 'Item1': 4, 'Item2': {'@type': 'Microsoft.Quantum.Chemistry.JordanWigner.JWOptimizedHTerms', 'Item1': [{'@type': 'Microsoft.Quantum.Chemistry.HTerm', 'Item1': [0], 'Item2': [0.17120128499999998]}, {'@type': 'Microsoft.Quantum.Chemistry.HTerm', 'Item1': [1], 'Item2': [-0.222796536]}, {'@type': 'Microsoft.Quantum.Chemistry.HTerm', 'Item1': [2], 'Item2': [0.17120128499999998]}, {'@type': 'Microsoft.Quantum.Chemistry.HTerm', 'Item1': [3], 'Item2': [-0.222796536]}], 'Item2': [{'@type': 'Microsoft.Quantum.Chemistry.HTerm', 'Item1': [0, 1], 'Item2': [0.12054614575]}, {'@type': 'Microsoft.Quantum.Chemistry.HTerm', 'Item1': [0, 2], 'Item2': …
```

Fields are case sensitive

---

Chemistry/src/DataModel/DataFormats/YAML.cs
Chemistry/src/DataModel/FermionTerm.cs

IntegralData (the datastructure representing a broombridge schema) is marked internal, but we would like to expose it to developers can manipulate broombridge data structures programmatically.
Made a small change to the internal representation to make it json friendly.
And fixing a bug on how FermionTerms check for Equals.

Making IntegralData as public and making it friendly to json encoding.

---

Interoperability/python/src/qsharp/__init__.py
Interoperability/python/src/qsharp/serialization.py
Interoperability/python/src/qsharp/tests/Operations.qs
Interoperability/python/src/qsharp/tests/test_iqsharp.py
Interoperability/python/src/qsharp/tests/test_serialization.py

Missing return statement when compiling more than one Q# snippet from Python.

---

Chemistry/src/DataModel/QSharpFormat/JordanWignerEncoding.cs
Chemistry/tests/DataModelTests/ToEvolutionSetTest.cs

Avoid relying on mutability in QArray constructor calls.

modifying contructor calls for QArray

---

Chemistry/src/DataModel/Extensions.cs

This PR fixes the chemistry data model to not depend on mutability of Q# arrays at the C# level.

Fix mutable array issue in chemistry data model.

---

Chemistry/src/DataModel/Extensions.cs

This PR provides an improved fix for #88 that no longer depends on extension methods on IEnumerable<T> to convert to QArray<T>.

Explicitly call new QArray.

---

Chemistry/src/DataModel/QSharpFormat/JordanWignerEncoding.cs

Avoid relying on System.Collections.Immutable

Using array instead of immutable array in driver

---

Standard/src/Arithmetic/Modular.qs

This PR updates one use of a deprecated function call.

Updates deprecated use of InverseMod in MultiplyByModularInteger

---

Build/step-build-libs.yml
Build/step-build-magic.yml
Numerics/src/Integer/Inversion.qs
build.yml

This PR adds a new build variable that allows for skipping tests with a queue-time setting. This is useful when quickly checking changes to build pipelines.

Add new skip tests variable.

---

Chemistry/src/DataModel/JsonSerialization/FermionWavefunctionJsonConverter.cs

Warning produced by API docs build here:
https://ops.microsoft.com/#/repos/643865e0-2060-8ac7-69ae-90a4b9fe57da?tabName=builds
`Warning occurred: Invalid file link:(~/api/HamiltonianTerm)..`

Fix incorrect Hamiltonian href

---

NuGet.Config
README.md
build.yml

This PR updates the readme and bumps the version number used for CI builds in preparation for using the prerelease feed at https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_packaging?_a=feed&feed=alpha.

Update README and bump version for using prerelease feed.

---

Chemistry/src/DataModel/DataModel.csproj
Chemistry/src/Jupyter/Jupyter.csproj
Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/DataModelTests/CSharpTests.csproj
Chemistry/tests/SamplesTests/SamplesTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Standard.csproj
Standard/tests/Standard.Tests.csproj

This PR parallels microsoft/qsharp-runtime#72 by updating package references to avoid downgrade errors with the upcoming 0.10 release.

Update packages to avoid downgrade errors

---

Chemistry/src/DataModel/DataModel.csproj
Chemistry/src/Jupyter/Jupyter.csproj
Numerics/src/Numerics.csproj
Standard/src/Standard.csproj

This PR enables storing compressed source files inside `PDB` files, so they can later be accessed using `System.Reflection.Metadata` without the need for internet connection.

Enabling all source inclusion with source link

---

MachineLearning/src/Runtime/Runtime.csproj
Standard/src/Arithmetic/Reflections.qs
Standard/src/Math/Functions.qs
Standard/src/Measurement/Reset.qs
Standard/tests/AmplitudeAmplificationTests.qs
Standard/tests/Arithmetic/ReflectionTests.qs
Standard/tests/ArrayTests.qs
Standard/tests/CombinatorTests.qs
Standard/tests/Logical/PredicateTests.qs
Standard/tests/Math/MathTests.qs
Standard/tests/Measurement/ResetTests.qs

This PR adds new unit tests to cover the functionality added to M.Q.Standard as a part of #176. In writing these tests, I also found and fixed a bug in ReflectAboutInteger that caused the operation to reflect about the binary negation of the given integer instead.

Unit tests for new operations and functions in M.Q.Standard used to support QML

---

.pre-commit-config.yaml
Build/check_indents.py

This PR adds initial support for using the [`pre-commit`](https://pre-commit.com/) library to filter out extraneous noise from diffs, including trailing whitespace as well as mixed spaces and tabs. Using this configuration, contributors with the pre-commit hooks installed will be notified when they accidently commit mixed tabs and spaces, and will be offered an ammended commit with the issue rectified.

Added initial pre-commit settings.

---

Standard/src/Arrays/Arrays.qs
Standard/src/Canon/Combinators/ApplyRepeatedOver.qs
Standard/src/Canon/CommonGates.qs
Standard/tests/ApplyRepeatedOverTests.qs
Standard/tests/ArrayTests.qs

This PR catches the QML feature branch up to master, and applies whitespace fixes detected by precommit (see #92 for details).

Update QML feature branch to master

---

Standard/src/Convert/Convert.qs

This should fix #166 by providing a more specific error message.

Clarify the restriction on the number of bits for IntAsBoolArray

---

Standard/src/Canon/And.qs
Standard/src/Canon/Combinators/ApplyMultiControlled.qs
Standard/src/Convert/Convert.qs
Standard/tests/ANDTests.qs

Quantum AND gates (a.k.a. CCNOT with constant target)

---

Standard/src/AmplitudeAmplification/AmplitudeAmplification.qs
Standard/src/AmplitudeAmplification/CommonOracles.qs
Standard/src/AmplitudeAmplification/Convert.qs
Standard/src/AmplitudeAmplification/Deprecated.qs
Standard/src/AmplitudeAmplification/StandardAlgorithms.qs
Standard/src/AmplitudeAmplification/Types.qs
Standard/src/Oracles/Convert.qs
Standard/src/Oracles/Types.qs
Standard/src/Preparation/UniformSuperposition.qs

This PR refactors the existing AA namespace to use the Q# style guide. As per #158, there's some more work to be done here, but this PR begins by working to follow standard naming conventions and to simplify implementations using new Q# features.

Refactor AA namespace to use Q# style guide

---

Standard/src/Canon/Enumeration/Deprecated.qs
Standard/src/Canon/Enumeration/Trotter.qs

This PR fixes #206 by adding in an appropriate `/// # Remark` noting the 𝑘–2𝑘 dichotomy. This PR also improves code quality in the Trotter–Suzuki decomposition feature more generally and renames `DecomposeIntoTimeStepsCA` → `DecomposedIntoTimeStepsCA` to reflect that this feature is a exposed as a **function** that returns a new evolution operation.

Fix #206 and improve Trotter–Suzuki code quality.

---

MachineLearning/src/Structure.qs
MachineLearning/tests/ClassificationTests.qs
MachineLearning/tests/StructureTests.qs
MachineLearning/tests/TypesTests.qs
MachineLearning/tests/ValidationTests.qs
Standard/src/Arithmetic/Comparators.qs
Standard/src/Arithmetic/Integer.qs
Standard/src/Diagnostics/Facts.qs
Standard/src/Simulation/Algorithms.qs

This PR improves test coverage for the QML library, introducing one additional needed fact as a part of that effort, and fixing one bug exposed in the process. This PR also eliminates some warnings elsewhere in the libraries that were bothering me during builds.

Improve QML test coverage.

---

.devcontainer/devcontainer.json

This PR adds a .devcontainer configuration that can be used with either VS Code Remote Development or Visual Studio Online, making it easier to have reproducible builds for development and contributions. In particular, as per discussions with @KittyYeungQ, this will make it easier for first-time contributors to get up and running quickly (especially at events), without having to worry about local setups.

Add devcontainer config.

---

Chemistry/src/Jupyter/BroombridgeMagic.cs
Chemistry/src/Jupyter/ChemistryEncodeMagic.cs
Chemistry/src/Jupyter/FermionHamiltonianMagic.cs
Chemistry/src/Jupyter/Jupyter.csproj
Chemistry/src/Jupyter/WavefunctionMagic.cs
Chemistry/tests/JupyterTests/BroombridgeMagicTests.cs
Chemistry/tests/JupyterTests/ChemistryEncodeMagicTests.cs
Chemistry/tests/JupyterTests/FermionHamiltonianMagicTests.cs

This PR parallels https://github.com/microsoft/QuantumKatas/pull/319 and updates the Microsoft.Quantum.Chemistry.Jupyter package to use Jupyter Core 1.3.

Update to Jupyter Core 1.3.

---

Standard/src/Canon/And.cs
Standard/tests/ANDTests.qs

This PR overrides the behaviour of `ApplyAnd` and `ApplyLowDepthAnd` to use the `CCNOT` behaviour when used with `ToffoliSimulator`.

Simulate ApplyAnd and ApplyLowDepthAnd classically

---

Chemistry/src/Metapackage/Metapackage.csproj
Chemistry/src/Runtime/Runtime.csproj
Chemistry/src/Tools/Tools.csproj

As a continuation of #295 , replacing the icon for three packages that were missed in the original asset update.

Replacing icon for packages that were missed in the recent asset update.

---

Chemistry/src/Metapackage/Metapackage.csproj

The Metapackage project contains no code, so disable creating the .snupkg symbols package for that project.

Disable .snupkg generation for Metapackage

---

Design/meetings/2020/api-design-2020-07-24.md

This PR adds notes from the 24 July 2020 Q# API Design meeting, including a resolution on the API design proposed in #304.

Added design meeting notes from 2020-07-24.

---

Standard/tests/ANDTests.qs
Standard/tests/ArithmeticTests.qs
Standard/tests/IntegerTests.qs
Standard/tests/QcvvTests.cs
Standard/tests/QeccTests.qs

Running all the standard tests could take 15+ mins, this changes tweaks some of the tests to instead of doing exhaustive validations, simply take some representative cases.

Tweak tests to decrease their duration

---

Build/props/tests.props
Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/src/MachineLearning.csproj
MachineLearning/tests/MachineLearningTests.csproj
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Canon/And.cs
Standard/src/Characterization/EstimateFrequency.cs
Standard/src/Diagnostics/Emulation/AllowOperationCalls.cs
Standard/src/Diagnostics/Emulation/AllowQubitAllocations.cs
Standard/src/Diagnostics/Emulation/Internal.cs
Standard/src/Standard.csproj
Standard/tests/Arrays/MapTests.cs
Standard/tests/Canon/ApplyToEachTests.cs
Standard/tests/Canon/CommonGatesTests.cs
Standard/tests/Standard.Tests.csproj
Visualization/src/Visualization.csproj

This updates the QuantumLibraries repo for the breaking changes to the Q# runtime that will be made by microsoft/qsharp-runtime#349:
* Wrap C# callable member names in underscores (e.g., `Body` -> `__Body__`, `Factory` -> `__Factory__`).
This shouldn't be merged until microsoft/qsharp-runtime#349 is merged.

Update C# callable implementations to use new naming conventions

---

Standard/src/Preparation/UniformSuperposition.qs

This is a proposal to fix #221. It adds an assertion that the input state is in state `|0...0>`. The assertion will also get triggered when calling the `Adjoint` variant on a state that is not in a uniform superposition. Ideally, we would check whether the state is eventually in a uniform superposition, but this may add too much overhead.

Improved assertion for PrepareUniformSuperposition

---

Standard/src/Canon/Combinators/ApplyToArray.qs

This implements the `ApplyTo{Head,Rest,Tail,Most}{,C,A,CA}` combinators described in #313.

Combinators for ApplyTo of an operation to Head, Tail, Rest, and Most of an array

---

Standard/src/Arrays/Unique.qs
Standard/tests/Arrays/UniqueTests.qs

This implements `Unique` from the proposal in #313.
Note that this function implements `Unique` wrt. the semantics, e.g., found in C++.
It returns an array with the same order but no adjacent equal elements. If one wants to have _truly_ unique arrays, one can combine this function with `Sorted` (mentioned in the docs).
If we want a different semantics, we might need to add a comparison function to check for order, or a more general comparison function that returns (-1 for `<`, 0 for `=`, and 1 for `>`).

Array function to filter for unique elements

---

Visualization/src/Visualization.csproj

This change improves the performance of loading the `Microsoft.Quantum.Standard.Visualization` package inside IQ# by telling NuGet to skip resolution of the IQ#-specific dependency.
This resolves https://github.com/microsoft/iqsharp/issues/338.

Add PrivateAssets="All" to IQ# package reference

---

Python/qsharp-chemistry/README.md
Python/qsharp/README.md

Following the example of microsoft/qsharp-compiler#671, this PR adds links to support and learning paths for the metadata for the `qsharp` and `qsharp-chemistry` PyPI packages.

Update docs for PyPI package descriptions

---

Standard/src/Canon/CommonGates.qs

Fix #278 CX truth table

---

Standard/src/Arithmetic/Integer.qs

PR for issue #335
Implemented controlled adder blocks following [this paper](https://arxiv.org/abs/1709.06648 ) but use the sum and carry blocks to compute the output carry bit.

RippleCarryAdderD update

---

Design/meetings/2020/api-design-2020-11-05.md

This PR adds review notes from the combined October / November 2020 Q# API review meeting. A discussion thread will be opened shortly and linked to from this PR.

Review notes for combined Oct/Nov meeting.

---

Standard/src/Arithmetic/Asserts.qs
Standard/src/Preparation/Arbitrary.qs
Standard/src/Preparation/Deprecated.qs
Standard/src/Preparation/Mixed.qs
Standard/src/Preparation/QuantumROM.qs
Standard/tests/QuantumROMTests.qs

This PR completes work started with https://github.com/microsoft/QuantumLibraries/issues/322 and #212, and as reviewed at #344. After this PR, we should be good to merge the relevant feature branch to `main`.

Implement last changes from #344

---

Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/src/MachineLearning.csproj
MachineLearning/tests/MachineLearningTests.csproj
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Preparation/Arbitrary.cs
Standard/src/Preparation/Arbitrary.qs
Standard/src/Standard.csproj
Standard/tests/Standard.Tests.csproj
Visualization/src/Visualization.csproj

Added new non-Adj/non-Ctr operation `_PrepareAmplitudesFromZeroState` that will emulate state preparation if running on a simulator that supports it and the prerequisites are met.
Had to move onto SDK 0.14.20111301-pull to pick up the new functionality in the Quantum Simulator.

Enable PrepareArbitraryState to use state injection on Quantum Simulator

---

build.yml

Add a `main` build scheduled for 1AM PST on Saturdays to keep component governance detection current.

Update build schedule

---

Standard/src/Convert/Convert.qs
Standard/tests/QuantumROMTests.qs

This PR slightly improves the `TestPurifiedMixedState` unit test to help diagnose failures such as that seen in https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=21163&view=logs&j=b78a1ffd-6a4f-5c9a-fd79-c70d65470011&t=a3b90293-a206-53fd-a1c1-8b7b4b27ab86.

Slight improvements to error handling in TestPurifiedMixedState.

---

Standard/src/Synthesis/MatrixUtils.cs
Standard/src/Synthesis/TwoLevelUnitary.cs
Standard/src/Synthesis/UnitaryDecomposition.cs
Standard/src/Synthesis/UnitaryDecomposition.qs
Standard/tests/Synthesis/UnitaryDecompositionTest.qs

This PR adds Q# operation which applies arbitrary gate specified by 2^n x 2^n unitary matrix on a qubit register, as requested in #291.
It's based on an algorithm which I have implemented in Python in [this repository](https://github.com/fedimser/quantum_decomp).
Implementation consists of 3 parts:
1. Implementing 1-qubit gate specified by 2x2 matrix - in native Q#.
2. Matrix decomposition algorithm, which decomposes unitary matrix as product of two-level unitary matrices with indices differing exactly in 1 bit - in C#.
3. Q# operation which uses decomposition in (2) and implements arbitrary n-qubit unitary via multiple calls to controlled (1) operation and X gates.
Complexity of this algorithm is O(N^3) and size of output is O(N^2), where N is size of matrix (N=2^n, where n is number of …

Add ApplyUnitary operation

---

Standard/src/Standard.csproj

With the ongoing refactor of the qsharp-runtime repo to support target packages, the Microsoft.Quantum.Simulators package no longer automatically brings in the Microsoft.Quantum.QSharp.Core package, so projects need to explicitly add that reference if they are have suppressed loading of the core package via `IncludeQsharpCorePackages` set to false. See microsoft/qsharp-runtime#476, which this change will help unblock.

Adding explicit reference to Qsharp.Core package

---

Standard/src/Math/Functions.qs
Standard/tests/Math/MathTests.qs

This PR fixes #403 by replacing the recursive implementation with an iterative one. However, reading @vadym-kl's issue description I wonder whether it is better to implement it as a Q# intrinsic and calling directly into C#'s method to retrieve the bit size.

Iterative BitSizeL implementation

---

Standard/src/Arithmetic/Modular.qs

Fixed typo and added clarifications of registers. 
This is used in the coming Learn module (and maybe as the example walk through an API ref page), so would ideally be merged ASAP.

Fix MultiplyAndAddByModularInteger 

---

Standard/src/Optimization/Univariate.qs
Standard/tests/Optimization/UnivariateTests.qs

This implements the change discussed in #286 and improves tests for `Optimization.LocalUnivariateMinimum`.
I also added the amount of queries made by the search into the output type. This value is mainly used in tests, but I suppose it can also be in the public API.
The amount of queries should now be ⌈log<sub>φ</sub>(|bounds|/tolerance)⌉ + 2. This made for a more straightforward implementation than one with only + 1. The algorithm may still never terminate if the tolerance is too small (non-positive, or small enough for precision issues to appear).

Improve LocalUnivariateMinimum

---

Standard/src/Preparation/Arbitrary.qs

The API documentation is taken from deprecated StatePreparationPositiveCoefficients (adjusted for the new operation signature). 
This fixes #384.

Fix PrepareArbitraryStateD API documentation

---

Standard/src/Arithmetic/Arithmetic.qs

It refers to the old operation `InPlaceXorLE` which it deprecates.

corrected invalid documentation reference in ApplyXorInPlace

---

NuGet.Config

Revert NuGet.config change as it introduced a break into end to end builds that wasn't caught by PR validations.

Revert "Update NuGet.Config (#425)"

---

Design/meetings/2021/api-design-2021-03-04.md

This PR adds notes from yesterday's API review. Will open a discussion thread momentarily.

Add notes from Mar 2021 API review.

---

.gitignore
Standard/src/Arrays/Multidimensional.qs

This works around https://github.com/microsoft/qsharp-compiler/issues/964 by avoiding passing `Length<'T>` as a callable paramter, where `'T` is an inherited generic type.

Work around for compiler QIR generaiton issue

---

Standard/src/Arithmetic/Modular.qs

I wonder if we should add a usage example as well, something along the lines of "If you want to compute |(3+2⋅x)mod 5⟩, you need to allocate an extra register sum in state |3⟩ and call MultiplyAndAddByModularInteger(2, 5, x, sum)"?

Fix API docs for MultiplyAndAddByModularInteger

---

Standard/src/Arithmetic/Measurement.qs

Removed reference to deprecated operation MeasureIntegerBE.

Fix API docs for MeasureInteger

---

Standard/src/Canon/Combinators/ApplyIf.qs
Standard/src/Canon/Combinators/CControlled.qs
Standard/tests/Synthesis.qs

Fixes #377.
This introduces a breaking change, since existing operations change the order of arguments.

ApplyIf gets consistent with ApplyIfElse

---

Standard/src/AmplitudeAmplification/AmplitudeAmplification.qs
Standard/src/AmplitudeAmplification/Deprecated.qs
Standard/src/Arithmetic/Deprecated.qs
Standard/src/Arrays/Filter.qs
Standard/src/Canon/Deprecated.qs
Standard/src/Characterization/Deprecated.qs
Standard/src/Preparation/QuantumROM.qs
Standard/src/Synthesis/ControlledOnTruthTable.qs
Standard/src/Synthesis/DecompositionBased.qs

@"" style of links doesn't seem to work if the reference is in lowercase.
Includes fixing broken formulas in PurifiedMixedState.

Fix broken links to API docs

---

Standard/src/Canon/Multiplexer.qs

The syntax for the `controlled` specialization is not consistent with the [grammar specification](https://github.com/microsoft/qsharp-language/blob/9cb9b91a49341d691c4fdc7d3f464453cc8eae36/Specifications/Language/5_Grammar/QSharpParser.g4#L103).

Change syntax with respect to grammar

---

Build/manifest.ps1
Chemistry/src/Tools/Tools.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/DataModelTests/DataModelTests.csproj
Chemistry/tests/JupyterTests/JupyterTests.csproj
Chemistry/tests/SamplesTests/SamplesTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/tests/MachineLearningTests.csproj
Numerics/tests/NumericsTests.csproj
Standard/tests/Standard.Tests.csproj

In accordance with the changes tracked by the issue below, we're updating the libraries to target .NET6
https://github.com/microsoft/qsharp-compiler/issues/1224

Update Quantum Libraries executables to .NET 6

---

MachineLearning/src/Properties/NamespaceInfo.qs

Currently the link "To learn more about this quantum machine learning library" at https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.machinelearning points to the same page, rather than to https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/machine-learning/intro. I believe changing the xref to UID from https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/libraries/machine-learning/intro.md should fix it.

Fix link to QML library intro

---

Build/e2e.yml

In order to keep build numbers consistent with upcoming changes in the qdk-release versions, we are removing the YYMM element for the patch version and using the buildId instead.

Y22K bug in package version

---

Standard/tests/QcvvTests.qs

Because of intermittent test failures, I propose to increase the tolerance for this test.
See:
```
X Microsoft.Quantum.Tests.TestRobustPhaseEstimation+QuantumSimulator.TestRobustPhaseEstimation [571ms] 
Error Message: 
Q# Test failed. For details see the Standard output below. 
Expected: True 
Actual: False 
Stack Trace: 
at Microsoft.Quantum.Tests.TestRobustPhaseEstimation.QuantumSimulator.TestRobustPhaseEstimation() in D:\a\1\s\submodules\QuantumLibraries\Standard\tests\QcvvTests.qs:line 104 
Standard Output Messages: 
Unhandled exception. Microsoft.Quantum.Simulation.Core.ExecutionFailException: Values were not equal within tolerance. 
Expected: 0.5235987755982988 
Actual: 0.5114440214174745 
---> Microsoft.Quantum.Tests.TestRobustPhaseEstimation on …
```

Set RobustPhaseEstimation test tolerance to 0.02

---

Build/manifest.ps1
Build/props/tests.props
Chemistry/src/Runtime/Runtime.csproj
Chemistry/src/Tools/Tools.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/DataModelTests/DataModelTests.csproj
Chemistry/tests/JupyterTests/JupyterTests.csproj
Chemistry/tests/SamplesTests/SamplesTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/src/MachineLearning.csproj
MachineLearning/tests/MachineLearningTests.csproj
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Standard.csproj
Standard/tests/Standard.Tests.csproj
Visualization/src/Visualization.csproj

We're migrating the QDK to the most recent Long Time Support version of the .NET framework. For details about this change, refer to the original issue [Q#C:1224](https://github.com/microsoft/qsharp-compiler/issues/1224).
As part of this change, we're:
- Re-targeting all .NetCoreApp3.1 binaries to .NET6.0
- Updating Docker images, samples and templates.
- Libraries using .NetStandard2.1 are not affected by this change.
- The minimum supported .NET version in the QDK will also be updated from 3.1 to 6.0
This is a multi-repo change, and all changes will need to be merged concurrently.

Update QDK to .NET6.0 (QuantumLibraries)

---

build.yml

This PR removes the $(yy:MM) field from all pipelines to keep consistency with the new qdk package version format.

Remove year:month from pipeline name field

---

.gitignore

Building the libraries projects generates API documentation in a docs/ folder. Our release workflows use these files to update documentation in a separate repository, but we never commit the generated files to the libraries repo itself, so it makes sense to add those files to gitignore.

Add docs/ folders to gitignore

---

Standard/src/AmplitudeAmplification/AmplitudeAmplification.qs
Standard/src/Canon/CommonGates.qs
Standard/src/Oracles/Types.qs

This PR optimizes some code in amplitude amplification (no execution of sequence `Adjoint Op; Op`) updates formatting to newer Q# language features. It also has some updates to documentation.

Optimization and formatting in amplitude amplification

---

Standard/src/Arrays/Arrays.qs
Standard/src/Arrays/Deprecated.qs
Standard/src/Arrays/Fold.qs
Standard/src/Arrays/Map.qs
Standard/src/Arrays/Sequence.qs
Standard/src/Arrays/Zip.qs
Standard/src/Canon/Combinators/ApplyToEach.qs
Standard/src/Canon/Combinators/Bind.qs
Standard/src/Canon/Combinators/RestrictedToSubregister.qs
Standard/src/Canon/Enumeration/Trotter.qs
Standard/src/Convert/Convert.qs
Standard/src/Diagnostics/Asserts.qs
Standard/src/ErrorCorrection/Types.qs
Standard/src/Math/Functions.qs
Standard/src/Oracles/Convert.qs
Standard/src/Preparation/Arbitrary.qs
Standard/src/Preparation/Deprecated.qs
Standard/src/Simulation/Data/GeneratorRepresentation.qs

Following up on discussion in #531, let's use `# Examples` consistently

Unify Markdown for Examples section

---

Standard/src/Arrays/Arrays.qs

Chunks: Add check that chunk size is positive

---

Numerics/src/Integer/Types.qs

Add note: SignedLittleEndian uses two's complement

---

.github/workflows/gh-sync.yml

The gh-sync GitHub Action allows you to synchronize public GitHub issues with internal ADO tracking. It can be customized to be triggered according to a repository's specific needs, see more below.
https://github.com/microsoft/gh-sync

Add gh-sync workflow

---

Numerics/src/FixedPoint/Convert.qs
Numerics/src/FixedPoint/Measurement.qs
Numerics/tests/FixedPointTests.qs

This also implements one function proposed in #559, however, kept `internal` as it has not been approved by API review.

Fixes #560

---

global.json

Changes on .Net 6.0.300 requires that a local global.json includes the version of the Quantum.Sdk otherwise projects that don't have it specified fail compilation, even if there is another global.json in their parent path.

Creating global.json

---

Standard/src/Canon/Utils/Multiplexer.qs
Standard/tests/Canon/Utils/MultiplexerTests.cs
Standard/tests/MultiplexerTests.qs

Previous counts (`numControls`, `tcount`, `width`) for `2^numControls` unitaries:
```
(1, 0, 6),
(2, 28, 8),
(3, 84, 10),
(4, 196, 12),
(5, 420, 14),
(6, 868, 16)
```
New counts:
```
(1, 0, 6),
(2, 8, 8),
(3, 24, 10),
(4, 56, 12),
(5, 120, 14),
(6, 248, 16)
```

Improves MultiplexOperations implementation

---

Standard/src/Arrays/Windows.qs

ApplyWindowed

---

Design/meetings/2022/api-design-2022-07.md

This is to perform the [asynchronous API review meeting](https://github.com/microsoft/QuantumLibraries/wiki/Q%23-API-Design-Process#async-api-review-meeting) for July 2022. The issues are listed as part of the meeting notes. Please feel free to leave comments or edits.

API review July 2022

---

Chemistry.sln
Chemistry/src/DataModel/OrbitalIntegral/OrbitalIntegral.cs
Chemistry/src/DataModel/OrbitalIntegral/OrbitalIntegralExtensions.cs
Chemistry/src/DataModel/Serialization/Broombridge/BroombridgeDataStructurev0.1.cs
Chemistry/src/DataModel/Serialization/Broombridge/BroombridgeDataStructurev0.3.cs
Chemistry/src/DataModel/Serialization/LegacyFormats/FciDump.cs
Chemistry/tests/DataModelTests/FermionTermTests/FermionHamiltonianTests.cs
Chemistry/tests/DataModelTests/SerializationTests/LiQuiDTests.cs
Chemistry/tests/SamplesTests/DocsSecondQuantization.cs

- Fixes for fourfold symmetry in v0.3.
- Added Symmetry as a property of OrbitalIntegral to simplify code.
- Updated DataModels tests for OrbitalIntegral Symmetry property.
Self-approving to facilitate beta testing.

Gulow/broombridge 0.3

---

Standard/src/Synthesis/ControlledOnTruthTable.qs

The links at https://learn.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.synthesis.applyxcontrolledontruthtable and https://learn.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.synthesis.applyxcontrolledontruthtablewithcleantarget are not recognized. I guess the capitalization in the @ link has to match the capitalization in the name exactly.

Fix broken links to CNOT

---

Standard/src/Convert/Convert.qs

Followed advice from @msoeken to add an example to ResultArrayAsInt function Microsoft Learn page.
Issue: Details or example lacking for ResultArrayAsInt function #635
https://learn.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.convert.resultarrayasint

Details or example lacking for ResultArrayAsInt function #635

---

Standard/src/Preparation/Mixed.qs

fix: #649 
The matrices `H` and `S` are not commutative. According to the code, `S` is applied after `H`. So, the correct order is `SH`.

Doc fix: matrix multiplication order for PauliY

---

Numerics/src/FixedPoint/Facts.qs

Two APIs in Fact.qs are out of work when the length of FixedPoint array is 2. Rest is proper to replace Most, in this way, this case will also be included to check.

Fix an array operation error of IdenticalFormatFactFxP and IdenticalPointPosFactFxP

---

Build/manifest.ps1
Chemistry/src/DataModel/DataModel.csproj
Chemistry/src/Jupyter/Jupyter.csproj
Chemistry/src/Metapackage/Metapackage.csproj
Chemistry/src/Runtime/Runtime.csproj
MachineLearning/src/MachineLearning.csproj
Numerics/src/Numerics.csproj
Standard/src/Standard.csproj
Visualization/src/Visualization.csproj

DevOps 48463, 48471.
The `netstandard2.1` target framework has undesirable dependencies, migrating the affected packages to `net6.0`.
Multi-repo PR:
[Q#Compiler](https://github.com/microsoft/qsharp-compiler/pull/1601), [Q#RT](https://github.com/microsoft/qsharp-runtime/pull/1121), [iQ#](https://github.com/microsoft/iqsharp/pull/760), [QuantumLibraries](https://github.com/microsoft/QuantumLibraries/pull/656), [Quantum-NC](https://github.com/microsoft/Quantum-NC/pull/84), [Quantum](https://github.com/microsoft/Quantum/pull/771) (samples), [Katas](https://github.com/microsoft/QuantumKatas/pull/868), QDK, and a private repo.
PR CI build can fail, but overall qdk.release (0.27.254480) has succeeded.

Fixing the undesirable dependencies issue for qdk.
