Canon/src/Multiplexer.qs
Canon/src/StatePreparation/QuantumROM.qs
Canon/src/StatePreparation/StatePreparation.qs

As discussed in https://github.com/MicrosoftDocs/quantum-docs-pr/pull/338.
Also fix a couple of typos.

Fix rendering of several StatePreparation formulas

---

Canon/src/Arithmetic/Integer.qs
Canon/tests/IntegerTests.qs

Added code for integer adders and greater than comparison with tests.

Arithmetic

---

Interoperability/python/src/qsharp/__init__.py
Interoperability/python/src/qsharp/clients/__init__.py
Interoperability/python/src/qsharp/clients/iqsharp.py

Checking that server is still alive before trying to execute any request (if it is not, it just hangs until it times out).
Adding a bunch of debug messages in the way.

IQ# auto-restart for Python and debug messages.

---

Interoperability/python/src/qsharp/__init__.py
Interoperability/python/src/qsharp/clients/iqsharp.py
Interoperability/python/src/qsharp/tomography.py
Interoperability/python/src/qsharp/types.py

This PR fixes bugs and adds features needed for the upcoming new tomography sample, including exposing new IQ# features in 0.5.1903.2703.

Update Python interoperability library to enable new tomography sample

---

Canon/src/Math/Random.qs

Clarify docs and fix normalization in Random.qs

---

Chemistry/src/Runtime/JordanWigner/JordanWignerBlockEncoding.qs
Chemistry/src/Runtime/JordanWigner/JordanWignerEvolutionSet.qs
Chemistry/src/Runtime/JordanWigner/JordanWignerOptimizedBlockEncoding.qs
Chemistry/src/Runtime/JordanWigner/OptimizedBEOperator.qs
Chemistry/tests/ChemistryTests/InitialStatePrepTests.qs
Standard/src/Arrays/Arrays.qs
Standard/src/Arrays/Enumeration.qs
Standard/src/Arrays/Filter.qs
Standard/src/Arrays/Fold.qs
Standard/src/Arrays/Map.qs
Standard/src/Arrays/Search.qs
Standard/src/Canon/Combinators/ApplyToEach.qs
Standard/src/Canon/Combinators/ApplyToEachIndex.qs
Standard/src/Canon/Combinators/Bind.qs
Standard/src/Canon/Utils/Paulis.qs
Standard/src/Math/Functions.qs
Standard/src/Measurement/Registers.qs
Standard/src/Preparation/Reference.qs
Standard/tests/ArrayTests.qs
Standard/tests/AssertTests.qs
Standard/tests/MathTests.qs
Standard/tests/MultiplexerTests.qs
Standard/tests/QFTTests.qs
Standard/tests/QcvvTests.qs
Standard/tests/QubitizationTests.qs

This PR introduces two new array functions, `IndexRange` and `Enumerated`, for working with arrays and ranges in `for` loops.

New array functions

---

Chemistry/src/DataModel/Extensions.cs
Chemistry/src/DataModel/QSharpFormat/JordanWignerEncoding.cs
Chemistry/src/Runtime/JordanWigner/JordanWignerBlockEncoding.qs
Chemistry/src/Runtime/JordanWigner/JordanWignerOptimizedBlockEncoding.qs
Chemistry/src/Runtime/JordanWigner/OptimizedBEOperator.qs
Chemistry/src/Runtime/JordanWigner/StatePreparation.qs
Standard/src/AmplitudeAmplification/AmplitudeAmplification.qs
Standard/src/Arithmetic/Measurement.qs
Standard/src/Arrays/Arrays.qs
Standard/src/Arrays/Filter.qs
Standard/src/Arrays/Map.qs
Standard/src/Arrays/Subarray.qs
Standard/src/Arrays/Zip.qs
Standard/src/Canon/DataStructures/Stack.qs
Standard/src/Canon/IterateThroughCartesianProduct.qs
Standard/src/Canon/Utils/Multiplexer.qs
Standard/src/Canon/Utils/Paulis.qs
Standard/src/Convert/Convert.qs
Standard/src/Math/Functions.qs
Standard/src/Preparation/QuantumROM.qs
Standard/src/Preparation/StatePreparation.qs
Standard/src/Simulation/Data/GeneratorRepresentation.qs
Standard/src/Simulation/PauliEvolutionSet.qs
Standard/tests/MultiplexerTests.qs
Standard/tests/QuantumROMTests.qs
Standard/tests/QubitizationTests.qs
Standard/tests/StatePreparationTests.qs

Specifically the changes to QArray.

Adapting to use the 0.65 simulation framework changes

---

Chemistry/src/DataModel/DataModel.csproj
Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/ChemistryTests.csproj
Chemistry/tests/DataModelTests/DataModelTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
Standard/src/Arithmetic/Modular.qs
Standard/src/Diagnostics/Facts.qs
Standard/src/Math/Deprecated.qs
Standard/src/Math/Functions.qs
Standard/src/Math/Types.qs
Standard/src/Standard.csproj
Standard/tests/ArithmeticTests.qs
Standard/tests/CombinatorTests.qs
Standard/tests/IntegerTests.qs
Standard/tests/Math/MathTests.qs
Standard/tests/MathTests.qs
Standard/tests/Standard.Tests.csproj

Begin adding more classical math functions for BigInt.

---

Standard/src/Arithmetic/Deprecated.qs
Standard/src/Canon/CommonGates.qs
Standard/tests/ArithmeticTests.qs
Standard/tests/ArrayTests.qs
Standard/tests/AssertTests.qs
Standard/tests/QeccTests.qs

Removes the lingering warnings from unittests.

Removing pending warnings from tests

---

Interoperability/python/src/qsharp/clients/__init__.py
Interoperability/python/src/qsharp/clients/iqsharp.py
Interoperability/python/src/qsharp/clients/mock.py

* Add user agent and mock client to Python.

Add user agent and mock client to Python. (#108)

---

Standard/src/Canon/Combinators/Bind.qs
Standard/src/Preparation/Reference.qs

* Fix formula in PrepareEntangledState operation (per https://github.com/MicrosoftDocs/quantum-docs-pr/issues/423)
* Fix code samples for Bound* operations

Fix two small issues in API documentation

---

Standard/src/Canon/Combinators/Delay.qs

Adding Delay combinator with a functional form

---

Standard/src/Canon/CommonGates.qs
Standard/tests/CommonGateTests.qs

Some notes 
- Right place to add the operation? 
- Is Fermionic SWAP the best name, or should we consider some variant that indicates the phase change?

[Small addition] Added Fermionic SWAP

---

Standard/src/Canon/Combinators/ApplyIf.qs

Update signatures of ApplyIfZeroCA and ApplyIfOneCA

---

Chemistry/src/DataModel/DataModel.csproj
Chemistry/src/Jupyter/Jupyter.csproj
Numerics/src/Numerics.csproj
Standard/src/Standard.csproj

Adding support for SourceLink and enabling XML documentation output 

---

Chemistry/src/DataModel/DataModel.csproj
Chemistry/src/Jupyter/Jupyter.csproj
Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/DataModelTests/CSharpTests.csproj
Chemistry/tests/SamplesTests/SamplesTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/src/DataModel/DataModel.csproj
MachineLearning/src/Runtime/Circuits.qs
MachineLearning/src/Runtime/Runtime.csproj
MachineLearning/src/Runtime/Training.qs
MachineLearning/src/Runtime/Types.qs
MachineLearning/src/Runtime/Validation.qs
MachineLearning/tests/MachineLearningTests.csproj
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Optimization/Properties/NamespaceInfo.qs
Standard/src/Optimization/Univariate.qs
Standard/src/Standard.csproj
Standard/tests/Optimization/UnivariateTests.qs
Standard/tests/Standard.Tests.csproj

This PR adds to the QML feature work a new function for deterministic optimization of deterministic univariate functions, as that logic is used widely throughout QML training loops to choose a bias value that minimizes the number of misclassifications in a given dataset. This new functionality is in a new namespace, Microsoft.Quantum.Optimization, to allow for the possible future addition of stochastic optimization or optimization of stochastic operations.

Bounded univariate minimization

---

Chemistry/src/DataModel/DataModel.csproj
Chemistry/src/Jupyter/Jupyter.csproj
Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/DataModelTests/CSharpTests.csproj
Chemistry/tests/SamplesTests/SamplesTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/src/DataModel/DataModel.csproj
MachineLearning/src/Runtime/Runtime.csproj
MachineLearning/tests/InputEncodingTests.qs
MachineLearning/tests/MachineLearningTests.csproj
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Standard.csproj
Standard/tests/Standard.Tests.csproj
build.yml

This PR adds a unit test to the QML library in preparation for testing QML functionality more broadly. This PR also updates the QML library and its dependencies to the new 0.10.1912.501 version of the compiler and runtime, in order to use the new `@Test("…")` attribute.

Add placeholder for QML unit tests.

---

Chemistry/src/DataModel/DataModel.csproj
Chemistry/src/Jupyter/Jupyter.csproj
Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/DataModelTests/CSharpTests.csproj
Chemistry/tests/JupyterTests/JupyterTests.csproj
Chemistry/tests/SamplesTests/SamplesTests.csproj
Chemistry/tests/SerializationTests/SerializationTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Standard.csproj
Standard/tests/Standard.Tests.csproj

Specifically the Newtonsoft package update is needed, since we updated it in the runtime.

Package updates

---

Standard/src/Arithmetic/Increment.qs

There appears to be no function IncrementByIntegerPhaseLE, and I guess it is covered by ApplyLEOperationOnPhaseLE.

Removed comment ref to IncrementByIntegerPhaseLE

---

Standard/src/Canon/Utils/ControlledOnBitString.qs

This change adds description, remarks and examples sections.

Improve API documentation for ControlledOnBitString

---

Standard/src/Arrays/Arrays.qs

Here is the preview link: https://review.docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays.constantarray?branch=tcNickolas-patch-1&view=qsharp-preview

Update API documentation for ConstantArray

---

Standard/src/Arrays/Any.qs

Adding an example snippet for Microsoft.Quantum.Arrays.Any documentation.
- quantum-docs-pr: [https://github.com/MicrosoftDocs/quantum-docs-pr/pull/708](https://github.com/MicrosoftDocs/quantum-docs-pr/pull/708)
- Build successful
- [Preview URL](https://review.docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays.any?view=qsharp-preview&branch=pr-en-us-708)

Updatating API documentation - Adding examples for Microsoft.Quantum.Arrays.Any

---

Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/src/MachineLearning.csproj
MachineLearning/src/Training.qs
MachineLearning/src/Types.qs
MachineLearning/tests/MachineLearningTests.csproj
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Standard.csproj
Standard/tests/Standard.Tests.csproj

This PR slightly refactors TrainSequentialClassifier and TrainSequentialClassifierAtModel to make it easier to use the latter directly from C#.

Slightly refactor bias updating to make TrainSequentialClassifierAtModel easier to use from C#.

---

Standard/src/Arrays/EqualA.qs
Standard/tests/ArrayTests.qs

This fixes https://github.com/microsoft/QuantumLibraries/issues/225.

Add function EqualA for testing array equality

---

.github/workflows/automerge.yml

This PR adds a new GitHub Action that automatically merges in pull requests that pass checks and reviews, using the "automerge" label.

Add new automerge action.

---

Standard/src/Diagnostics/Facts.qs
Standard/src/Diagnostics/Properties/NamespaceInfo.qs
Standard/src/Diagnostics/Quantum.qs

Noticed inconsistency in white space, fixed some copyright headers in same folder along the way.

Small fixes for white space and copyright headers

---

Standard/src/Arithmetic/Integer.qs
Standard/tests/IntegerTests.qs

This PR fixes a bug in the CDKM adder. The tests didn't catch the bug, because integer tests were not executed. The PR enables these tests.

Fixes bug in CDKM adder

---

README.md

The README currently points to uservoice. I changed it re-using the wording from the qsharp-compiler project.

Update feature request possibilities in README

---

Chemistry/src/Runtime/JordanWigner/JordanWignerOptimizedBlockEncoding.qs
Chemistry/src/Runtime/JordanWigner/OptimizedBEOperator.qs
Standard/src/Arithmetic/Asserts.qs
Standard/src/Canon/And.qs
Standard/src/Characterization/EstimateFrequency.cs
Standard/src/Diagnostics/Emulation/DataStructures.cs
Standard/src/Diagnostics/Emulation/Extensions.cs
Standard/src/Diagnostics/Emulation/Internal.cs
Standard/src/Math/Random.qs
Standard/src/Synthesis/ControlledOnTruthTable.qs
Standard/tests/AmplitudeAmplificationTests.qs
Standard/tests/CommonGateTests.qs
Standard/tests/Diagnostics/DumpTests.cs
Standard/tests/MultiplexerTests.qs
Standard/tests/QcvvTests.qs
Standard/tests/QeccTests.qs
Standard/tests/QubitizationTests.qs
Standard/tests/StatePreparationTests.qs
Standard/tests/UniformSuperpositionPreparationTests.qs

Fixes several warnings in Standard.sln and addresses #317.

Fix several warnings

---

Standard/src/Canon/Utils/Multiplexer.qs

Fixes documentation in MultiplexPauli

---

Build/manifest.ps1

As I was validating the signed dlls on e2e, noticed that this dll is missing signing.

Missing dll for signing

---

Chemistry/src/Jupyter/Jupyter.csproj

Turns out we were missing it from the manifest for a reason...

Signing config for Jupyter magic dll

---

Python/qsharp-chemistry/qsharp_chemistry/__init__.py
Python/qsharp-chemistry/qsharp_chemistry/broombridge.py
Python/qsharp-chemistry/qsharp_chemistry/fermion_hamiltonian.py
Python/qsharp-chemistry/qsharp_chemistry/problem_description.py
Python/qsharp-chemistry/qsharp_chemistry/shims.py
Python/qsharp-chemistry/qsharp_chemistry/tests/test_chemistry.py
Python/qsharp/qsharp/chemistry/__init__.py

One function to load a Broombridge file and generate a tuple to pass as `JWEncodedData`.

Consolidate Chemistry data wrangling tools into one function

---

Python/qdk-chemistry/qdk_chemistry/geometry/__init__.py
Python/qdk-chemistry/qdk_chemistry/geometry/geometry.py
Python/qdk-chemistry/qdk_chemistry/solvers/nwchem.py
Python/qdk-chemistry/qdk_chemistry/solvers/openmolcas.py
Python/qdk-chemistry/qdk_chemistry/solvers/psi4.py
Python/qdk-chemistry/qdk_chemistry/solvers/util.py
Python/qdk-chemistry/qdk_chemistry/tests/test_nwchem.py
Python/qdk-chemistry/qdk_chemistry/tests/test_openmolcas.py
Python/qdk-chemistry/qdk_chemistry/tests/test_psi4.py

Add functions to generate Psi4 and OpenMolcas input format

Add Psi4 and OpenMolcas codegen functionality

---

Standard/src/Convert/Convert.qs

Fix 'positive's that should be 'non-negative's in comments

---

Standard/src/Preparation/QuantumROM.qs

Do not apply negative keepCoeff in QROM

---

Standard/src/AmplitudeAmplification/AmplitudeAmplification.qs

Fixes #414 and addresses some deprecations on the way.

Address optimization in ApplyObliviousAmplitudeAmplification

---

Standard/src/Canon/Combinators/Curry.qs
Standard/tests/CombinatorTests.qs

This PR implements enhancement #406, as approved in the February API review (see #412).

Implement #406.

---

Build/props/tests.props

This PR prevents unit test projects from contributing to API documentation.

Disable generating API documentation from unit test projects.

---

Standard/src/Synthesis/UnitaryDecomposition.qs

* Add usage sample
* Render the formulas in description as formulas

Improve API documentation for ApplyUnitary

---

Design/meetings/2021/api-design-2021-05-11.md

This PR adds notes from yesterday's API review. Will open a discussion thread momentarily.

Add notes from May API design review.

---

MachineLearning/src/Properties/NamespaceInfo.qs
Standard/src/Diagnostics/Properties/NamespaceInfo.qs
Standard/src/Measurement/Properties/NamespaceInfo.qs
Standard/src/Oracles/Convert.qs

Also makes _ReflectionOracleFromDeterministicStateOracle internal, following the example of #470.

Add namespace info to several namespaces

---

Standard/src/Arrays/Fold.qs

Added `...` indicating multiple function applications to match `...` indicating multiple arguments.

Fix formula in Fold documentation

---

Standard/src/Arithmetic/Integer.qs
Standard/src/Convert/Convert.qs
Standard/src/Math/Functions.qs
Standard/tests/ConversionTests.qs
Standard/tests/Math/SpecialFunctionTests.qs

This PR fixes several small bugs in special functions for limiting cases and adds corresponding tests.
Closes #500, #503, #505, and #506.

Various small fixes to special functions

---

Standard/src/Math/Functions.qs
Standard/tests/Math/MathTests.qs

Handle special case mod = 1 in ExpModI

---

Standard/src/Bitwise/Properties/NamespaceInfo.qs
Standard/src/Canon/Properties/NamespaceInfo.qs
Standard/src/Characterization/Properties/NamespaceInfo.qs
Standard/src/Convert/Properties/NamespaceInfo.qs
Standard/src/ErrorCorrection/Properties/NamespaceInfo.qs
Standard/src/Logical/Properties/NamespaceInfo.qs
Standard/src/Math/Properties/NamespaceInfo.qs

This fixes #496, and includes part of the #483.

Add namespace summaries and descriptions.

---

Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/src/MachineLearning.csproj
MachineLearning/tests/MachineLearningTests.csproj
NOTICE.txt
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Diagnostics/Emulation/Internal.cs
Standard/src/Standard.csproj
Standard/tests/Standard.Tests.csproj
Visualization/src/Visualization.csproj

PRs:
[Q#RT](https://github.com/microsoft/qsharp-runtime/pull/918)
[QuantumLibraries](https://github.com/microsoft/QuantumLibraries/pull/521)
[iqsharp](https://github.com/microsoft/iqsharp/pull/586)
[Quantum](https://github.com/microsoft/Quantum/pull/606)
[qdk](https://github.com/microsoft/qdk/pull/214)

Adapting for the QuantumSimulator change

---

Chemistry/src/Runtime/Runtime.csproj
Chemistry/tests/ChemistryTests/QSharpTests.csproj
Chemistry/tests/SystemTests/SystemTests.csproj
MachineLearning/src/MachineLearning.csproj
MachineLearning/tests/MachineLearningTests.csproj
NOTICE.txt
Numerics/src/Numerics.csproj
Numerics/tests/NumericsTests.csproj
Standard/src/Diagnostics/Emulation/Internal.cs
Standard/src/Standard.csproj
Standard/tests/Standard.Tests.csproj
Visualization/src/Visualization.csproj

* Adapting for a callback signature change in QuantumSimulator.
* Switched to BigInteger index.

Adapting for the QuantumSimulator change (#521)

---

Numerics/src/Integer/Multiplication.qs
Standard/src/Canon/Combinators/ApplyMultiControlled.qs

A recent PR has implemented an operation that already existed.

Refactor and remove duplicate internal operation

---

Standard/src/Preparation/QuantumROM.qs

Fixes #570

---

Numerics/src/FixedPoint/Addition.qs
Numerics/src/FixedPoint/Comparison.qs
Numerics/src/FixedPoint/Facts.qs
Numerics/src/FixedPoint/Init.qs
Numerics/src/FixedPoint/Measurement.qs
Numerics/src/FixedPoint/Multiplication.qs
Numerics/src/FixedPoint/Polynomial.qs
Numerics/src/FixedPoint/Types.qs

Also refactors the code to make use of the new names and some optimizations on the way

Implements #549

---

Numerics/src/FixedPoint/Convert.qs
Numerics/src/FixedPoint/Init.qs

Fixes #559; also rewrites `PrepareFxP` using new function.

Implements fixed-point conversion functions

---

Standard/src/AmplitudeAmplification/AmplitudeAmplification.qs

Fixes #580 and also incorporates some style changes.

Fixes documentation for ObliviousAmplitudeAmplificationFromStatePreparation

---

.github/workflows/devskim.yml
Design/meetings/2022/api-design-2022-04.md
Numerics/src/FixedPoint/Convert.qs
Numerics/tests/FixedPointTests.qs
Standard/src/AmplitudeAmplification/AmplitudeAmplification.qs
Standard/src/Math/Functions.qs
Standard/src/Preparation/QuantumROM.qs

This merges `main` into the feature branch and also adds examples to fixed-point conversion functions as discussed in April 2022 API review.

Feature branch cleanup

---

.github/workflows/devskim.yml
Design/meetings/2022/api-design-2022-04.md
Numerics/src/FixedPoint/Addition.qs
Numerics/src/FixedPoint/Comparison.qs
Numerics/src/FixedPoint/Convert.qs
Numerics/src/FixedPoint/Facts.qs
Numerics/src/FixedPoint/Init.qs
Numerics/src/FixedPoint/Measurement.qs
Numerics/src/FixedPoint/Multiplication.qs
Numerics/src/FixedPoint/Polynomial.qs
Numerics/src/FixedPoint/Types.qs
Numerics/tests/FixedPointTests.qs
Standard/src/AmplitudeAmplification/AmplitudeAmplification.qs
Standard/src/Math/Functions.qs
Standard/src/Preparation/QuantumROM.qs

This PR is to merge recently approved fixed-point arithmetic PRs from a feature branch into `main`. All API in the PRs have been approved in the April API review.

Merging fixed-point arithmetic feature branch

---

Numerics/src/FixedPoint/LookupTable.qs
Numerics/tests/LookupTableTests.qs

Taking the fix we need for release.

Revise ApplyFunctionWithLookupTable (#617)

---

Standard/src/Preparation/Arbitrary.qs

Fixes https://github.com/microsoft/QuantumLibraries/issues/622

Fixes outdated example

---

Build/props/tests.props
Chemistry/tests/DataModelTests/DataModelTests.csproj
Chemistry/tests/JupyterTests/JupyterTests.csproj
Chemistry/tests/SamplesTests/SamplesTests.csproj

**Multi-repo PR:**
[Q#C](https://github.com/microsoft/qsharp-compiler/pull/1607), [Q#RT](https://github.com/microsoft/qsharp-runtime/pull/1128), [iQ#](https://github.com/microsoft/iqsharp/pull/770), [Katas](https://github.com/microsoft/QuantumKatas/pull/873), [QLib](https://github.com/microsoft/QuantumLibraries/pull/657), [Q](https://github.com/microsoft/Quantum/pull/781), [Q-NC](https://github.com/microsoft/Quantum-NC/pull/85), private repo, QDK.
DevOps items 48477, 48480, 48478.

Upgraded "Microsoft.NET.Test.Sdk" and "xunit.runner.visualstudio".
